export interface ProductMaterialOption {
  id: string;
  name: string;
  colorHex: string;
  texture?: string;
}

export interface ChekadbamProduct {
  id: string;
  code: string;
  name: string;
  category: "planting" | "furniture" | "structures" | "water_fire" | "lighting" | "flooring" | "accessories";
  categoryName: string;
  shortDesc: string;
  fullDesc: string;
  dimensions: {
    width: number; // in meters (for 3D studio)
    depth: number;
    height: number;
    unitString: string; // e.g. "۱۲۰ × ۴۰ × ۴۵ سانتی‌متر"
  };
  weightKg: number;
  deadLoadRating: "light" | "medium" | "heavy";
  priceEstToman: number;
  materials: {
    wpcColors?: ProductMaterialOption[];
    metalColors?: ProductMaterialOption[];
    plantTypes?: string[];
    stoneTypes?: string[];
  };
  model3D: {
    shapeType: "box" | "cylinder" | "bench_integrated" | "bench_backrest" | "lounge_set" | "pergola" | "pergola_deck" | "green_wall" | "green_wall_planter" | "water_feature" | "firepit" | "firepit_table" | "bbq" | "tree" | "shrub" | "louver" | "umbrella" | "light_pole" | "deck_tile";
    primaryColor: string;
    secondaryColor: string;
    hasLighting?: boolean;
    lightColor?: string;
    lightIntensity?: number;
    foliageColor?: string;
  };
  features: string[];
  specs: { [key: string]: string };
  image: string;
  gallery: string[];
  cadAvailable: boolean;
  isPopular?: boolean;
}

export const WPC_COLORS: ProductMaterialOption[] = [
  { id: "walnut", name: "گردویی شکلاتی (Dark Walnut)", colorHex: "#4a321f" },
  { id: "teak", name: "تیک طبیعی / شنی (Natural Teak)", colorHex: "#9b683e" },
  { id: "charcoal", name: "دودی ذغالی (Charcoal Ash)", colorHex: "#2b2a29" },
  { id: "oak", name: "بلوطی روشن (Light Oak)", colorHex: "#c59d6f" },
];

export const METAL_COLORS: ProductMaterialOption[] = [
  { id: "black", name: "مشکی مات الکترواستاتیک", colorHex: "#1a1a1a" },
  { id: "charcoal", name: "طوسی متالیک تیره", colorHex: "#374151" },
  { id: "cream", name: "کرم شنی استخوانی", colorHex: "#d6cebe" },
];

export const CHEKADBAM_PRODUCTS: ChekadbamProduct[] = [
  // 1. Planting Systems
  {
    id: "fb-80",
    code: "CK-FB-080",
    name: "فلاورباکس مدولار ۸۰ سانتی‌متری",
    category: "planting",
    categoryName: "سیستم کاشت مدولار",
    shortDesc: "فلاورباکس پرتابل با بدنه چوب‌پلاست WPC و استراکچر داخلی فلز گالوانیزه ضدزنگ با مخزن ذخیره آب.",
    fullDesc: "فلاورباکس مدولار ۸۰ چکادبام به صورت کاملاً پرتابل و مستقل طراحی شده است. بدون نیاز به تخریب یا ایزولاسیون مجدد بام، مستقیماً روی پایه‌های ترازکننده قرار می‌گیرد. دارای ژئوتکستایل فیلتر، دریناژ هوشمند و مخزن ذخیره آب جهت کاهش دفعات آبیاری.",
    dimensions: { width: 0.8, depth: 0.4, height: 0.45, unitString: "۸۰ × ۴۰ × ۴۵ سانتی‌متر" },
    weightKg: 28,
    deadLoadRating: "light",
    priceEstToman: 4200000,
    materials: {
      wpcColors: WPC_COLORS,
      metalColors: METAL_COLORS,
      plantTypes: ["بوته‌های همیشه سبز", "اسطوخودوس و رزماری", "شمشاد طلایی", "پیچ امین‌الدوله"],
    },
    model3D: {
      shapeType: "box",
      primaryColor: "#5c3d23",
      secondaryColor: "#1a1a1a",
      foliageColor: "#2e7d32",
    },
    features: [
      "مخزن ذخیره آب و فیلتراسیون درین",
      "بدنه چوب‌پلاست مقاوم در برابر اشعه UV",
      "عایق حرارتی دو جداره ریشه گیاه",
      "اتصال پازلی به سایر ماژول‌ها و نیمکت‌ها",
    ],
    specs: {
      "جنس بدنه": "چوب‌پلاست WPC گرید A با روکش ضد سایش",
      "استراکچر داخلی": "پروفیل گالوانیزه گرم با رنگ پودری الکترواستاتیک",
      "لایه زهکشی": "شانه تخم‌مرغی پلی‌اتیلن + ژئوتکستایل ۳۰۰ گرمی",
      "گنجایش خاک": "حدود ۱۱۰ لیتر بستر سبک‌ساز مخصوص بام",
      "گارانتی": "۵ سال ضمانت بی‌قیدوشرط سازه و رنگ",
    },
    image: "/images/products/flowerbox-modular-wpc.svg",
    gallery: [
      "/images/products/flowerbox-modular-wpc.svg",
      "https://images.pexels.com/photos/8091888/pexels-photo-8091888.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    cadAvailable: true,
    isPopular: true,
  },
  {
    id: "fb-120",
    code: "CK-FB-120",
    name: "فلاورباکس مدولار ۱۲۰ سانتی‌متری",
    category: "planting",
    categoryName: "سیستم کاشت مدولار",
    shortDesc: "پرفروش‌ترین ابعاد استاندارد کاشت روف‌گاردن با قابلیت ادغام روشنایی خطی زیرین.",
    fullDesc: "طول ۱۲۰ سانتی‌متری این ماژول امکان کاشت ترکیبی درختچه‌های کوتاه به همراه گیاهان پوششی و رونده را فراهم می‌کند. قابلیت اتصال مستقیم به نیمکت‌های ۱۲۰ و دیواره‌های سبز لووردار.",
    dimensions: { width: 1.2, depth: 0.45, height: 0.5, unitString: "۱۲۰ × ۴۵ × ۵۰ سانتی‌متر" },
    weightKg: 42,
    deadLoadRating: "medium",
    priceEstToman: 6100000,
    materials: {
      wpcColors: WPC_COLORS,
      metalColors: METAL_COLORS,
      plantTypes: ["یاس هلندی", "زرشک زینتی و کامیس", "یوکا و نسترن", "ترکیب گیاهان فصلی"],
    },
    model3D: {
      shapeType: "box",
      primaryColor: "#5c3d23",
      secondaryColor: "#1a1a1a",
      hasLighting: true,
      lightColor: "#ffdd99",
      foliageColor: "#1b5e20",
    },
    features: [
      "ابعاد بهینه برای کاشت درختچه‌های تزیینی",
      "شیار مخفی برای نصب نور خطی LED زیرین",
      "پایه‌های رگلاژ شونده برای سطوح با شیب‌بندی",
      "سیستم آبیاری قطره‌ای توکار مخفی",
    ],
    specs: {
      "جنس بدنه": "چوب‌پلاست پروفیل توپر ضد رطوبت",
      "حجم خاک سبک": "۱۸۰ لیتر لایت‌سویل غنی‌شده",
      "عایق ریشه": "لایه نفوذناپذیر Root Barrier",
      "وزن اشباع با خاک و آب": "حدود ۱۶۰ کیلوگرم",
      "گارانتی": "۵ سال تعویض قطعات",
    },
    image: "https://images.pexels.com/photos/36721032/pexels-photo-36721032.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    gallery: [
      "https://images.pexels.com/photos/36721032/pexels-photo-36721032.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    cadAvailable: true,
    isPopular: true,
  },
  {
    id: "fb-160",
    code: "CK-FB-160",
    name: "فلاورباکس مدولار ۱۶۰ سانتی‌متری عریض",
    category: "planting",
    categoryName: "سیستم کاشت مدولار",
    shortDesc: "فلاورباکس بزرگ مقیاس برای جانمایی در حاشیه جان‌پناه و تفکیک فضاهای بزرگ روف‌گاردن.",
    fullDesc: "ابعاد ۱۶۰ سانتی‌متری به عنوان المان مرزی و حصار سبز طبیعی عمل کرده و مانع از دید مستقیم به حریم خصوصی می‌شود. طراحی تقویت‌شده با تیرک‌های میانی ضدخمش.",
    dimensions: { width: 1.6, depth: 0.5, height: 0.55, unitString: "۱۶۰ × ۵۰ × ۵۵ سانتی‌متر" },
    weightKg: 58,
    deadLoadRating: "medium",
    priceEstToman: 7900000,
    materials: {
      wpcColors: WPC_COLORS,
      metalColors: METAL_COLORS,
      plantTypes: ["بامبو خیزران", "پیروکانتا پرپشت", "ترکیب همیشه سبز چندطبقه"],
    },
    model3D: {
      shapeType: "box",
      primaryColor: "#4a321f",
      secondaryColor: "#1a1a1a",
      foliageColor: "#2e7d32",
    },
    features: [
      "ایده‌آل برای ایجاد دیوار سبز حائل و حفظ محرمیت",
      "استحکام فوق‌العاده در برابر بارهای جانبی باد",
      "انشعابات توکار زهکشی سریع",
    ],
    specs: {
      "گنجایش خاک": "۲۹۰ لیتر بستر ارگانیک بام",
      "اتصالات": "پیچ و مهره استیل ۳۰۴ ضدزنگ",
      "گارانتی": "۵ سال",
    },
    image: "https://images.pexels.com/photos/8091888/pexels-photo-8091888.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    gallery: ["https://images.pexels.com/photos/8091888/pexels-photo-8091888.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"],
    cadAvailable: true,
  },
  {
    id: "fb-corner",
    code: "CK-FB-CNR",
    name: "فلاورباکس کنج ۹۰ درجه مدولار",
    category: "planting",
    categoryName: "سیستم کاشت مدولار",
    shortDesc: "باکس زاویه‌دار گوشه برای استفاده حداکثری از کنج‌های بلااستفاده بام و بالکن.",
    fullDesc: "طراحی L شکل این باکس اجازه می‌دهد چیدمان فلاورباکس‌های محیطی در گوشه‌ها بدون شکست یا فضای خالی ناقص ادامه پیدا کند.",
    dimensions: { width: 0.9, depth: 0.9, height: 0.5, unitString: "۹۰ × ۹۰ × ۵۰ سانتی‌متر" },
    weightKg: 44,
    deadLoadRating: "medium",
    priceEstToman: 6800000,
    materials: {
      wpcColors: WPC_COLORS,
      metalColors: METAL_COLORS,
      plantTypes: ["درختچه زینتی بونسای", "افرا ژاپنی", "ترکیب گل ناز و شمشاد"],
    },
    model3D: {
      shapeType: "box",
      primaryColor: "#5c3d23",
      secondaryColor: "#1a1a1a",
      foliageColor: "#33691e",
    },
    features: [
      "پوشش کامل کنج‌های ۹۰ درجه جان‌پناه",
      "طراحی یکپارچه بدون درز بازدارنده",
      "نقطه کانونی عالی برای کاشت درختچه شاخص",
    ],
    specs: {
      "ابعاد هر بال": "۹۰ در ۴۵ سانتی‌متر",
      "وزن خالی": "۴۴ کیلوگرم",
      "گارانتی": "۵ سال",
    },
    image: "https://images.pexels.com/photos/7587879/pexels-photo-7587879.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    gallery: ["https://images.pexels.com/photos/7587879/pexels-photo-7587879.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"],
    cadAvailable: true,
  },
  // 2. Outdoor Furniture
  {
    id: "bn-120",
    code: "CK-BN-120",
    name: "نیمکت مدولار چوب‌پلاست ۱۲۰",
    category: "furniture",
    categoryName: "مبلمان فضای باز",
    shortDesc: "نیمکت ساده و مینیمال با نشیمن WPC توپر و پایه‌های فلزی مشکی مات.",
    fullDesc: "نیمکت مدولار ۱۲۰ سانتی‌متری با طراحی زاویه‌ای مدرن. امکان نصب روشنایی خطی مخفی در زیر نشیمن، جلوه خیره‌کننده‌ای در شب به پشت‌بام شما می‌بخشد.",
    dimensions: { width: 1.2, depth: 0.45, height: 0.45, unitString: "۱۲۰ × ۴۵ × ۴۵ سانتی‌متر" },
    weightKg: 24,
    deadLoadRating: "light",
    priceEstToman: 4800000,
    materials: {
      wpcColors: WPC_COLORS,
      metalColors: METAL_COLORS,
    },
    model3D: {
      shapeType: "box",
      primaryColor: "#5c3d23",
      secondaryColor: "#111827",
      hasLighting: true,
      lightColor: "#fef08a",
      lightIntensity: 1.2,
    },
    features: [
      "نشیمن چوب‌پلاست مقاوم به لکه و آب‌وهوا",
      "نور مخفی گرم در زیر سازه نیمکت",
      "امکان اتصال سر به سر برای ایجاد ردیف نشیمن طولانی",
    ],
    specs: {
      "ظرفیت": "۲ الی ۳ نفر",
      "تحمل بار وزنی": "۳۵۰ کیلوگرم",
      "شاسی": "پروفیل صنعتی سنگین با پوشش فسفاته و رنگ کوره",
      "گارانتی": "۵ سال",
    },
    image: "https://images.pexels.com/photos/7587879/pexels-photo-7587879.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    gallery: ["https://images.pexels.com/photos/7587879/pexels-photo-7587879.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"],
    cadAvailable: true,
    isPopular: true,
  },
  {
    id: "bn-integrated",
    code: "CK-BN-INT",
    name: "مجموعه ترکیبی نیمکت متصل به دو فلاورباکس",
    category: "furniture",
    categoryName: "مبلمان فضای باز",
    shortDesc: "پکیج کامل نشیمن مهار شده بین دو فلاورباکس جانبی همراه با نورپردازی متمرکز.",
    fullDesc: "این ماژول نوآورانه نشیمن مرکزی را بین دو فلاورباکس طرفین تلفیق کرده و حس نشستن در احاطه عطر و طراوت گیاهان سبز را خلق می‌کند.",
    dimensions: { width: 2.2, depth: 0.5, height: 0.6, unitString: "۲۲۰ × ۵۰ × ۶۰ سانتی‌متر" },
    weightKg: 76,
    deadLoadRating: "medium",
    priceEstToman: 11900000,
    materials: {
      wpcColors: WPC_COLORS,
      metalColors: METAL_COLORS,
      plantTypes: ["رز هلندی و پیچ تلگرافی", "گیاهان معطر رزماری و نعنا زینتی"],
    },
    model3D: {
      shapeType: "bench_integrated",
      primaryColor: "#5c3d23",
      secondaryColor: "#1a1a1a",
      hasLighting: true,
      lightColor: "#ffe699",
      foliageColor: "#2e7d32",
    },
    features: [
      "ترکیب یکپارچه مبلمان و فضای سبز در یک محصول",
      "کاهش اتصالات و افزایش زیبایی بصری",
      "کابل‌کشی توکار آماده اتصال به کلید برق یا فتوسل هوشمند",
    ],
    specs: {
      "طول نشیمن مفید": "۱۲۰ سانتی‌متر",
      "ابعاد هر باکس جانبی": "۵۰ در ۵۰ سانتی‌متر",
      "گارانتی": "۵ سال تمام قطعات",
    },
    image: "/images/products/bench-integrated-wpc.svg",
    gallery: [
      "/images/products/bench-integrated-wpc.svg",
      "https://images.pexels.com/photos/7587884/pexels-photo-7587884.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    cadAvailable: true,
    isPopular: true,
  },
  {
    id: "bn-backrest",
    code: "CK-BN-BR140",
    name: "نیمکت پشتی‌دار اسلت چوب‌پلاست با شاسی مشکی",
    category: "furniture",
    categoryName: "مبلمان فضای باز",
    shortDesc: "نیمکت مدرن با نشیمن و پشتی اسلت‌های افقی چوب‌پلاست و شاسی فلزی مشکی مات با پایه‌های اسکی (Sled).",
    fullDesc: "این نیمکت با تیغه‌های افقی چوب‌پلاست و فاصله‌گذاری منظم بین اسلت‌ها طراحی شده تا آب باران به‌سرعت تخلیه شده و هوا در زیر نشیمن جریان داشته باشد. پشتی زاویه‌دار روی براکت‌های فلزی مشکی مهار شده و شاسی پایه از نوع اسکی با تیرک‌های رابط افقی است که فشار نقطه‌ای روی کف روف‌گاردن را به‌شکل چشمگیری کاهش می‌دهد و بدون نیاز به پیچ‌کردن در کف نصب می‌شود.",
    dimensions: { width: 1.4, depth: 0.62, height: 0.88, unitString: "۱۴۰ × ۶۲ × ۸۸ سانتی‌متر (ارتفاع نشیمن ۴۵)" },
    weightKg: 38,
    deadLoadRating: "light",
    priceEstToman: 9800000,
    materials: {
      wpcColors: WPC_COLORS,
      metalColors: METAL_COLORS,
    },
    model3D: {
      shapeType: "bench_backrest",
      primaryColor: "#a4551f",
      secondaryColor: "#18181b",
      hasLighting: false,
    },
    features: [
      "نشیمن و پشتی از اسلت‌های افقی چوب‌پلاست با درز تخلیه آب",
      "پشتی زاویه‌دار ارگونومیک روی براکت‌های فلزی مشکی",
      "پایه اسکی با تیرک رابط و کفشک پهن، بدون آسیب به عایق بام",
      "مقاوم در برابر تابش آفتاب، رطوبت و تغییر رنگ",
      "قابلیت چیدمان پشت‌به‌پشت یا خطی در مسیرهای حرکتی",
    ],
    specs: {
      "جنس نشیمن و پشتی": "پروفیل چوب‌پلاست WPC توپر با سطح شیاردار",
      "شاسی": "قوطی فولادی ۴۰×۲۰ با رنگ کوره‌ای مشکی مات",
      "ارتفاع نشیمن از کف": "۴۵ سانتی‌متر استاندارد ارگونومیک",
      "تحمل بار": "۳۵۰ کیلوگرم",
      "گارانتی": "۵ سال سازه و ثبات رنگ",
    },
    image: "/images/products/bench-slatted-backrest.svg",
    gallery: [
      "/images/products/bench-slatted-backrest.svg",
      "/images/products/bench-integrated-wpc.svg",
    ],
    cadAvailable: true,
    isPopular: true,
  },
  {
    id: "fp-table-square",
    code: "CK-FP-SQ110",
    name: "میز آتشدان مربعی چوب‌پلاست با سبد شعله فلزی",
    category: "water_fire",
    categoryName: "آب و نور و آتش",
    shortDesc: "میز آتشدان مربع با صفحه اسلت چوب‌پلاست، پایه جعبه‌ای تمام‌چوب و سبد شعله مشکی با سنگ‌های لاوا.",
    fullDesc: "ترکیبی از میز نشیمن و آتشدان گازی در یک ماژول واحد. صفحه میز از تیغه‌های باریک چوب‌پلاست با شیارهای ظریف ساخته شده و پایه جعبه‌ای آن محل استقرار مخزن گاز و شیر تنظیم را به‌طور کامل مخفی می‌کند. سبد شعله فولادی مشکی با میله‌های قوسی در مرکز میز قرار می‌گیرد و سنگ‌های آذرین لاوا حرارت را به‌صورت یکنواخت پخش می‌کنند.",
    dimensions: { width: 1.1, depth: 1.1, height: 0.72, unitString: "۱۱۰ × ۱۱۰ × ۷۲ سانتی‌متر" },
    weightKg: 92,
    deadLoadRating: "medium",
    priceEstToman: 21500000,
    materials: {
      wpcColors: WPC_COLORS,
      metalColors: METAL_COLORS,
    },
    model3D: {
      shapeType: "firepit_table",
      primaryColor: "#a4551f",
      secondaryColor: "#18181b",
      hasLighting: true,
      lightColor: "#f97316",
      lightIntensity: 3.2,
    },
    features: [
      "صفحه میز از اسلت‌های باریک چوب‌پلاست مقاوم به حرارت",
      "سبد شعله فولادی مشکی با میله‌های قوسی و سنگ لاوا",
      "پایه جعبه‌ای با محفظه مخفی مخزن گاز و شیر تنظیم",
      "شعله پاک و بدون دود، مناسب پشت‌بام و تراس",
      "شیر قطع‌کن ایمنی و ترموکوپل حرارتی",
    ],
    specs: {
      "جنس صفحه و بدنه": "چوب‌پلاست WPC ضد آب با مقاومت حرارتی سطح",
      "سبد شعله": "فولاد با رنگ کوره‌ای مشکی مات نسوز",
      "سوخت": "گاز شهری NG یا گاز مایع LPG",
      "توان حرارتی": "۴۰,۰۰۰ BTU",
      "گارانتی": "۳ سال برنر و ۵ سال بدنه",
    },
    image: "/images/products/firepit-gas-table.svg",
    gallery: [
      "/images/products/firepit-gas-table.svg",
      "/images/products/pergola-wpc-3x3.svg",
    ],
    cadAvailable: true,
    isPopular: true,
  },
  {
    id: "ln-set",
    code: "CK-LN-SET04",
    name: "ست مبل راحتی ۴ نفره چوب‌پلاست و فلز مشکی (با میز جلو مبلی)",
    category: "furniture",
    categoryName: "مبلمان فضای باز",
    shortDesc: "ست کامل مبلمان راحتی شامل کاناپه دونفره، دو عدد مبل تک‌نفره و میز جلو مبلی با شاسی لوپ مشکی، اسلت چوب‌پلاست و تشک‌های کرم بژ Sunbrella.",
    fullDesc: "این ست مبلمان لوکس فضای باز شامل یک کاناپه دونفره راحت، دو عدد صندلی راحتی تک‌نفره و یک میز جلو مبلی هماهنگ است. اسکلت اصلی از قوطی فولادی صنعتی با پوشش الکترواستاتیک مشکی مات ساخته شده و ساختار پایه آن از نوع اسکی (Sled Frame) با دسته‌های حلقه‌ای مدرن است. نشیمن و تکیه‌گاه مبل‌ها دارای بستر اسلت‌های افقی چوب‌پلاست WPC بوده و تشک‌های ضخیم و فوق‌العاده راحت با پارچه نانو آب‌گریز Sunbrella به رنگ کرم بژ شنی، راحتی بی‌نظیری در روف‌گاردن و تراس فراهم می‌کنند.",
    dimensions: { width: 2.2, depth: 1.5, height: 0.78, unitString: "۲۲۰ × ۱۵۰ × ۷۸ سانتی‌متر (ست کامل ۴ نفره)" },
    weightKg: 64,
    deadLoadRating: "light",
    priceEstToman: 26500000,
    materials: {
      wpcColors: WPC_COLORS,
      metalColors: METAL_COLORS,
    },
    model3D: {
      shapeType: "lounge_set",
      primaryColor: "#e8e2d5",
      secondaryColor: "#18181b",
    },
    features: [
      "ست کامل ۴ نفره: ۱ کاناپه دونفره + ۲ مبل تک‌نفره + ۱ میز جلو مبلی",
      "کلاف فولادی مستحکم با رنگ کوره‌ای مشکی مات و دسته‌های لوپ یکپارچه",
      "زیرسازی نشیمن و تکیه‌گاه با اسلت‌های مقاوم چوب‌پلاست WPC",
      "تشک‌های ضخیم فوم سرد قالبی با روکش پارچه نانو ضدآب و ضدلک Sunbrella کرم",
      "میز جلو مبلی با صفحه اسلت چوب‌پلاست شیاردار مقاوم در برابر حرارت و ظروف داغ",
    ],
    specs: {
      "ترکیب ست": "کاناپه دو نفره (۱۲۰cm) + دو مبل تک‌نفره (۶۵cm) + میز جلو مبلی (۹۵×۵۵cm)",
      "جنس شاسی": "قوطی فولادی صنعتی ۴۰×۲۰ با رنگ پودری الکترواستاتیک مشکی مات",
      "جنس اسلت‌ها": "چوب‌پلاست WPC توپر گرید A با روکش ضد سایش",
      "پارچه تشک‌ها": "اکریلیک رنگ‌شده در تاروپود Sunbrella آب‌گریز و ضد اشعه UV",
      "گارانتی": "۵ سال سازه و اتصالات، ۳ سال پارچه و فوم",
    },
    image: "/images/products/bench-slatted-backrest.svg",
    gallery: [
      "/images/products/bench-slatted-backrest.svg",
      "/images/products/pergola-wpc-3x3.svg",
    ],
    cadAvailable: true,
    isPopular: true,
  },
  // 3. Pergolas & Structures
  {
    id: "pg-3x3",
    code: "CK-PG-3030",
    name: "پرگولا مدولار مدرن چوب‌پلاست ۳×۳ متر",
    category: "structures",
    categoryName: "سایبان و پرگولا",
    shortDesc: "پرگولا پیش‌ساخته پرتابل با تیرک‌های ترکیبی آلومینیوم و WPC، سیستم مهار باد بدون سوراخکاری سقف.",
    fullDesc: "پرگولای ۳×۳ چکادبام بدون نیاز به جوشکاری در محل، با اتصالات مهندسی پیچ و مهره گالوانیزه مونتاژ می‌شود. پایه‌های وزنی مهندسی شده با فلاورباکس‌های کف، بادگیر بودن سازه را بدون سوراخ کردن ایزوگام تضمین می‌کند.",
    dimensions: { width: 3.0, depth: 3.0, height: 2.5, unitString: "۳۰۰ × ۳۰۰ × ۲۵۰ سانتی‌متر" },
    weightKg: 280,
    deadLoadRating: "heavy",
    priceEstToman: 38500000,
    materials: {
      wpcColors: WPC_COLORS,
      metalColors: METAL_COLORS,
    },
    model3D: {
      shapeType: "pergola",
      primaryColor: "#1e293b",
      secondaryColor: "#5c3d23",
      hasLighting: true,
      lightColor: "#ffe699",
      lightIntensity: 2.0,
    },
    features: [
      "مهار کامل سازه بر اساس تحلیل دینامیکی بار باد تا ۱۰۰ کیلومتر بر ساعت",
      "شیارهای آماده عبور سیم‌کشی و اسپات‌لایت‌های گرم توکار",
      "سازگار با سقف‌های شفاف پلی‌کربنات UV دار",
      "مونتاژ کامل در کمتر از یک روز کاری",
    ],
    specs: {
      "پروفیل ستون‌ها": "قوطی ۱۰۰×۱۰۰ میلی‌متر ضخامت ۲.۵ با کاور WPC",
      "تیرهای سقفی": "لوورهای چوب‌پلاست تقویت‌شده با هسته آلومینیومی",
      "پوشش رنگ": "الکترواستاتیک سوپر دورابل مقاوم به تابش تند آفتاب",
      "گارانتی": "۱۰ سال سازه و اتصالات",
    },
    image: "/images/products/pergola-wpc-3x3.svg",
    gallery: [
      "/images/products/pergola-wpc-3x3.svg",
      "https://images.pexels.com/photos/7587884/pexels-photo-7587884.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
      "https://images.pexels.com/photos/19075386/pexels-photo-19075386.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    cadAvailable: true,
    isPopular: true,
  },
  {
    id: "pg-deck-320",
    code: "CK-PG-DK320",
    name: "پرگولا مدولار چوب‌پلاست با کف‌سازی دک یکپارچه ۳.۲×۳.۲",
    category: "structures",
    categoryName: "سایبان و پرگولا",
    shortDesc: "پرگولا کامل با سکوی دک چوب‌پلاست، ستون‌های فولادی مشکی جفتی و تیرهای سرتاسری با سرهای بیرون‌زده.",
    fullDesc: "این ماژول یک واحد کامل و خودایستا است که سکوی کف، ستون‌ها و سقف لوور را یکجا در بر می‌گیرد. سکوی دک از تایل‌های چوب‌پلاست شیاردار با قاب دورگرد ساخته شده و ستون‌های فولادی مشکی به‌صورت جفت‌پروفیل در چهار گوشه مستقر می‌شوند. تیرهای اصلی چوب‌پلاست به‌صورت دوتایی در طرفین تیرک فولادی مشکی بسته می‌شوند و سرهای بیرون‌زده و پله‌ای آن‌ها جزئیات معماری شاخص این پرگولا را می‌سازد. تیرچه‌های عرضی و اسلت‌های نازک بالایی، سایه‌اندازی شطرنجی زیبایی روی کف ایجاد می‌کنند.",
    dimensions: { width: 3.2, depth: 3.2, height: 2.6, unitString: "۳۲۰ × ۳۲۰ × ۲۶۰ سانتی‌متر (با سکوی دک)" },
    weightKg: 410,
    deadLoadRating: "heavy",
    priceEstToman: 52000000,
    materials: {
      wpcColors: WPC_COLORS,
      metalColors: METAL_COLORS,
    },
    model3D: {
      shapeType: "pergola_deck",
      primaryColor: "#a4551f",
      secondaryColor: "#18181b",
      hasLighting: true,
      lightColor: "#ffe699",
      lightIntensity: 2.4,
    },
    features: [
      "سکوی دک چوب‌پلاست یکپارچه با قاب دورگرد و زهکشی زیرین",
      "ستون‌های جفت‌پروفیل فولادی با رنگ کوره‌ای مشکی مات",
      "تیرهای اصلی دوتایی چوب‌پلاست با سرهای پله‌ای بیرون‌زده",
      "تیرچه‌های عرضی و اسلت بالایی برای سایه‌اندازی شطرنجی",
      "نصب کاملاً پرتابل بدون سوراخ‌کاری عایق بام",
    ],
    specs: {
      "سازه ستون": "جفت قوطی فولادی ۶۰×۶۰ با رنگ الکترواستاتیک مشکی",
      "تیرهای سقف": "پروفیل چوب‌پلاست تقویت‌شده با هسته آلومینیومی",
      "کف‌سازی": "تایل چوب‌پلاست شیاردار روی پایه‌های رگلاژ",
      "مساحت سایه‌انداز": "حدود ۱۰.۲ مترمربع",
      "گارانتی": "۱۰ سال سازه و اتصالات",
    },
    image: "/images/products/pergola-wpc-3x3.svg",
    gallery: [
      "/images/products/pergola-wpc-3x3.svg",
      "/images/products/bench-slatted-backrest.svg",
    ],
    cadAvailable: true,
    isPopular: true,
  },
  {
    id: "gw-frame-planter",
    code: "CK-GW-FP120",
    name: "دیوار سبز مدولار قاب‌دار با تراف کاشت پایه",
    category: "structures",
    categoryName: "سایبان و سازه",
    shortDesc: "پارتیشن سبز خودایستا با قاب چوب‌پلاست، تراف کاشت فلزی مشکی و پنل رشد گیاه رونده.",
    fullDesc: "این ماژول یک پارتیشن سبز کاملاً پرتابل و خودایستا است. قاب بیرونی از پروفیل چوب‌پلاست با گوشه‌های فارسی‌بر ساخته شده و در پایین آن یک تراف کاشت فولادی مشکی با روکش چوب‌پلاست قرار دارد. پنل مشبک پشتی امکان بالا رفتن گیاهان رونده مانند پیچ انگور زینتی و پیچ امین‌الدوله را فراهم می‌کند تا طی یک فصل رشد، قاب به یک دیوار سبز زنده تبدیل شود. مناسب برای تفکیک فضا، ایجاد محرمیت و پوشاندن دیوارهای نامناسب بدون هیچ‌گونه نصب روی دیوار.",
    dimensions: { width: 1.2, depth: 0.42, height: 1.8, unitString: "۱۲۰ × ۴۲ × ۱۸۰ سانتی‌متر" },
    weightKg: 68,
    deadLoadRating: "medium",
    priceEstToman: 11200000,
    materials: {
      wpcColors: WPC_COLORS,
      metalColors: METAL_COLORS,
      plantTypes: ["پیچ انگور زینتی", "پیچ امین‌الدوله", "یاس رونده", "عشقه و پتوس مقاوم"],
    },
    model3D: {
      shapeType: "green_wall_planter",
      primaryColor: "#a4551f",
      secondaryColor: "#18181b",
      hasLighting: true,
      lightColor: "#fef08a",
      lightIntensity: 1.4,
      foliageColor: "#2e7d32",
    },
    features: [
      "قاب چوب‌پلاست با گوشه‌های فارسی‌بر و جزئیات دقیق",
      "تراف کاشت فولادی مشکی با روکش چوب‌پلاست و زهکشی",
      "پنل مشبک پشتی جهت هدایت رشد گیاهان رونده",
      "خودایستا و پرتابل، بدون نیاز به نصب روی دیوار",
      "قابلیت چیدمان کنار هم برای ساخت دیوار سبز پیوسته",
    ],
    specs: {
      "قاب": "پروفیل چوب‌پلاست WPC ضد UV با اتصالات استیل",
      "تراف کاشت": "ورق فولادی گالوانیزه با رنگ کوره‌ای مشکی",
      "گنجایش خاک": "حدود ۸۵ لیتر بستر سبک مخصوص بام",
      "آبیاری": "آماده اتصال به سیستم قطره‌ای توکار",
      "گارانتی": "۵ سال سازه و ثبات رنگ",
    },
    image: "/images/products/flowerbox-modular-wpc.svg",
    gallery: [
      "/images/products/flowerbox-modular-wpc.svg",
      "/images/products/bench-integrated-wpc.svg",
    ],
    cadAvailable: true,
    isPopular: true,
  },
  {
    id: "gw-120",
    code: "CK-GW-120",
    name: "دیواره سبز عمودی مدولار (Green Wall) با آبیاری قطره‌ای",
    category: "structures",
    categoryName: "سایبان و سازه",
    shortDesc: "دیوار سبز مستقل خودایستا با پنل‌های کاشت نمدی و آبیاری هوشمند چرخشی.",
    fullDesc: "دیوار سبز چکادبام به عنوان المان تفکیک فضا یا پوشش دیوارهای نامناسب همسایه عمل می‌کند. مجهز به سامانه آبیاری تحت فشار و سنسور رطوبت برای مصرف بهینه آب.",
    dimensions: { width: 1.2, depth: 0.25, height: 2.0, unitString: "۱۲۰ × ۲۵ × ۲۰۰ سانتی‌متر" },
    weightKg: 85,
    deadLoadRating: "medium",
    priceEstToman: 12500000,
    materials: {
      metalColors: METAL_COLORS,
      plantTypes: ["پوتوس ابلق", "سرخس و آگلونما", "عشقه مینیاتوری", "ترکیب فیتونیا و برگ‌انجیری"],
    },
    model3D: {
      shapeType: "green_wall",
      primaryColor: "#1b5e20",
      secondaryColor: "#1e293b",
      hasLighting: true,
      lightColor: "#fef08a",
      lightIntensity: 1.0,
      foliageColor: "#2e7d32",
    },
    features: [
      "سیستم مدار بسته بازچرخانی آب درین",
      "نور موضعی LED مخصوص رشد گیاهان (Grow Light)",
      "جداکننده صوتی و بصری بی‌نظیر برای روف‌گاردن‌ها",
    ],
    specs: {
      "تراکم گیاهی": "۳۶ تا ۴۸ بوته در هر مترمربع",
      "سیستم پمپاژ": "پمپ بی‌صدا ۱۲ ولت ایمن با تایمر دیجیتال",
      "گارانتی": "۲ سال سامانه آبیاری و ۵ سال استراکچر",
    },
    image: "https://images.pexels.com/photos/8091888/pexels-photo-8091888.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    gallery: ["https://images.pexels.com/photos/8091888/pexels-photo-8091888.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"],
    cadAvailable: true,
    isPopular: true,
  },
  {
    id: "pt-wpc",
    code: "CK-PT-160",
    name: "پارتیشن لوور چوب‌پلاست مدولار",
    category: "structures",
    categoryName: "سایبان و سازه",
    shortDesc: "جداکننده لوور چوبی با زوایای قابل تنظیم برای شکستن باد و حفظ حریم خصوصی.",
    fullDesc: "این پارتیشن اجازه عبور ملایم نسیم را داده اما دید مستقیم را محدود می‌کند. ایده‌آل برای جداسازی بخش نشیمن از تأسیسات و چیلرهای پشت‌بام.",
    dimensions: { width: 1.6, depth: 0.15, height: 1.8, unitString: "۱۶۰ × ۱۵ × ۱۸۰ سانتی‌متر" },
    weightKg: 42,
    deadLoadRating: "light",
    priceEstToman: 6400000,
    materials: {
      wpcColors: WPC_COLORS,
      metalColors: METAL_COLORS,
    },
    model3D: {
      shapeType: "louver",
      primaryColor: "#5c3d23",
      secondaryColor: "#111827",
    },
    features: [
      "کاهش سرعت بادهای شدید پشت‌بام",
      "بدون نیاز به نگهداری و رنگ‌آمیزی سالانه",
      "نصب سریع و بدون تخریب",
    ],
    specs: {
      "جنس لوورها": "پروفیل توخالی WPC مقاوم به خمیدگی",
      "فواصل تیغه‌ها": "۵ سانتی‌متر استاندارد آکوستیک و بصری",
      "گارانتی": "۵ سال",
    },
    image: "https://images.pexels.com/photos/7587884/pexels-photo-7587884.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    gallery: ["https://images.pexels.com/photos/7587884/pexels-photo-7587884.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"],
    cadAvailable: true,
  },

  // 4. Water & Fire Features
  {
    id: "wf-line",
    code: "CK-WF-FRM130",
    name: "آبنمای قاب دوبل چوب‌پلاست با حوضچه ریزش آب",
    category: "water_fire",
    categoryName: "آب و نور و آتش",
    shortDesc: "آبنمای پرتابل با حوضچه مربعی چوب‌پلاست، دو قاب پله‌ای سرریز آب بارانی و نورپردازی مخفی.",
    fullDesc: "این آبنما از یک حوضچه پایه چوب‌پلاست شیاردار با گوشه‌های فارسی‌بر و دو قاب عمودی چوب‌پلاست پله‌ای با ارتفاع‌های متفاوت تشکیل شده است. آب از نازل‌های خطی بالای هر قاب به‌صورت پرده‌های زلال و بارانی به حوضچه می‌ریزد. دارای مخزن مداربسته، فیلتراسیون ضد جلبک و پمپ بی‌صدا ۲۴ ولت.",
    dimensions: { width: 1.3, depth: 1.1, height: 1.45, unitString: "۱۳۰ × ۱۱۰ × ۱۴۵ سانتی‌متر" },
    weightKg: 82,
    deadLoadRating: "medium",
    priceEstToman: 22800000,
    materials: {
      wpcColors: WPC_COLORS,
      metalColors: METAL_COLORS,
    },
    model3D: {
      shapeType: "water_feature",
      primaryColor: "#a4551f",
      secondaryColor: "#38bdf8",
      hasLighting: true,
      lightColor: "#38bdf8",
      lightIntensity: 2.5,
    },
    features: [
      "دو قاب عمودی چوب‌پلاست پله‌ای با ریزش آب مستقل",
      "حوضچه پایه با روکش چوب‌پلاست شیاردار و عایق کامل",
      "نازل‌های پرده آب استیل ۳۰۴ ضدرسوب",
      "نورپردازی زیرآبی LED ضدآب IP68 با جلوه کریستالی",
      "مخزن مداربسته بدون نیاز به لوله‌کشی و تخریب سقف",
    ],
    specs: {
      "جنس قاب و بدنه": "چوب‌پلاست WPC گرید A با ساختار ضد رطوبت",
      "تعداد قاب‌های سرریز": "۲ قاب پله‌ای (ارتفاع ۱۴۵ و ۱۰۸ سانتی‌متر)",
      "حجم مخزن آب": "۱۲۰ لیتر مداربسته",
      "توان پمپ": "۵۵ وات بی‌صدا",
      "گارانتی": "۲ سال پمپ و ۵ سال بدنه",
    },
    image: "/images/products/water-feature-linear.svg",
    gallery: [
      "/images/products/water-feature-linear.svg",
      "/images/products/pergola-wpc-3x3.svg",
    ],
    cadAvailable: true,
    isPopular: true,
  },
  {
    id: "fp-round",
    code: "CK-FP-SQ110",
    name: "میز آتشدان مربعی چوب‌پلاست با سبد شعله فلزی",
    category: "water_fire",
    categoryName: "آب و نور و آتش",
    shortDesc: "میز آتشدان مربع با صفحه اسلت چوب‌پلاست، پایه جعبه‌ای تمام‌چوب و سبد شعله مشکی با سنگ‌های لاوا.",
    fullDesc: "ترکیبی از میز نشیمن و آتشدان گازی در یک ماژول واحد. صفحه میز از تیغه‌های باریک چوب‌پلاست با شیارهای ظریف ساخته شده و پایه جعبه‌ای آن محل استقرار مخزن گاز و شیر تنظیم را به‌طور کامل مخفی می‌کند. سبد شعله فولادی مشکی با میله‌های قوسی در مرکز میز قرار می‌گیرد و سنگ‌های آذرین لاوا حرارت را به‌صورت یکنواخت پخش می‌کنند.",
    dimensions: { width: 1.1, depth: 1.1, height: 0.72, unitString: "۱۱۰ × ۱۱۰ × ۷۲ سانتی‌متر" },
    weightKg: 92,
    deadLoadRating: "medium",
    priceEstToman: 21500000,
    materials: {
      wpcColors: WPC_COLORS,
      metalColors: METAL_COLORS,
    },
    model3D: {
      shapeType: "firepit",
      primaryColor: "#a4551f",
      secondaryColor: "#18181b",
      hasLighting: true,
      lightColor: "#f97316",
      lightIntensity: 3.2,
    },
    features: [
      "صفحه میز از اسلت‌های باریک چوب‌پلاست مقاوم به حرارت",
      "سبد شعله فولادی مشکی با میله‌های قوسی و سنگ لاوا",
      "پایه جعبه‌ای با محفظه مخفی مخزن گاز و شیر تنظیم",
      "شعله پاک و بدون دود، مناسب پشت‌بام و تراس",
      "شیر قطع‌کن ایمنی و ترموکوپل حرارتی",
    ],
    specs: {
      "جنس صفحه و بدنه": "چوب‌پلاست WPC ضد آب با مقاومت حرارتی سطح",
      "سبد شعله": "فولاد با رنگ کوره‌ای مشکی مات نسوز",
      "سوخت": "گاز شهری NG یا گاز مایع LPG",
      "توان حرارتی": "۴۰,۰۰۰ BTU",
      "گارانتی": "۳ سال برنر و ۵ سال بدنه",
    },
    image: "/images/products/firepit-gas-table.svg",
    gallery: [
      "/images/products/firepit-gas-table.svg",
      "/images/products/pergola-wpc-3x3.svg",
    ],
    cadAvailable: true,
    isPopular: true,
  },

  // 5. Lighting & Electrical
  {
    id: "lt-linear",
    code: "CK-LT-LIN",
    name: "چراغ خطی ال‌ای‌دی ضدآب زیر نیمکت و فلاورباکس",
    category: "lighting",
    categoryName: "روشنایی و برق",
    shortDesc: "لاین نوری آلومینیومی ۲۴ ولت ایمن با سیلیکون ضدآب IP67 و نور گرم ۳۰۰۰ کلوین.",
    fullDesc: "نورپردازی زیرین باعث شناور دیده شدن المان‌ها در شب شده و حس آرامش و عمق بی‌نظیری به پشت‌بام شما می‌بخشد.",
    dimensions: { width: 1.2, depth: 0.03, height: 0.03, unitString: "طول ۱۲۰ سانتی‌متر" },
    weightKg: 1.5,
    deadLoadRating: "light",
    priceEstToman: 1450000,
    materials: {},
    model3D: {
      shapeType: "light_pole",
      primaryColor: "#fef08a",
      secondaryColor: "#334155",
      hasLighting: true,
      lightColor: "#fef08a",
      lightIntensity: 2.5,
    },
    features: [
      "ولتاژ ایمن ۲۴ ولت بدون خطر برق‌گرفتگی در فضای باز",
      "نور کاملاً یکنواخت بدون افتادن لکه نوری (Dot-Free)",
      "سازگار با سنسورهای هوشمند تاریکی و دیمر",
    ],
    specs: {
      "دمای رنگ": "۳۰۰۰ کلوین آفتابی گرم یا ۴۰۰۰ کلوین نچرال",
      "استاندارد عایق": "IP67 ضد غبار و پاشش مستقیم آب",
      "طول عمر چیپ": "۵۰,۰۰۰ ساعت",
    },
    image: "https://images.pexels.com/photos/19075386/pexels-photo-19075386.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    gallery: ["https://images.pexels.com/photos/19075386/pexels-photo-19075386.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"],
    cadAvailable: true,
  },

  // 6. Flooring
  {
    id: "fl-wpc",
    code: "CK-FL-WPC",
    name: "تایل کف‌پوش چوب‌پلاست WPC پازلی رگلاژدار",
    category: "flooring",
    categoryName: "کف‌سازی مدولار",
    shortDesc: "تایل چوب‌پلاست شیاردار ضدلغزش با زیره پلیمری دریناژ سرخود جهت خروج سریع آب باران.",
    fullDesc: "پوشش کف روف‌گاردن چکادبام به صورت خشک‌چین و بدون ملات روی پایه‌های ترازکننده نصب می‌شود. به دلیل وزن کم و قابلیت زهکشی زیرین، آب باران به سادگی به سمت کف‌شور هدایت شده و به هیچ عنوان آب‌ماندگی ایجاد نمی‌کند.",
    dimensions: { width: 1.0, depth: 1.0, height: 0.04, unitString: "هر مترمربع (تایل‌های ۳۰×۳۰ پازلی)" },
    weightKg: 18, // per m2
    deadLoadRating: "light",
    priceEstToman: 2400000,
    materials: {
      wpcColors: WPC_COLORS,
    },
    model3D: {
      shapeType: "deck_tile",
      primaryColor: "#5c3d23",
      secondaryColor: "#3f2716",
    },
    features: [
      "نصب خشک‌چین بدون ملات و چسب",
      "دسترسی سریع به لایه‌های زیرین ایزوگام در صورت نیاز",
      "ضدلغزش در هنگام خیسی و بارندگی",
      "گارانتی ۱۰ ساله مقاومت در برابر پوسیدگی و حشرات",
    ],
    specs: {
      "ضخامت پروفیل": "۲۵ میلی‌متر توپر گرید اکستروژن سنگین",
      "تحمل وزن نقطه‌ای": "۱۵۰۰ کیلوگرم بر مترمربع",
      "گارانتی": "۱۰ سال تعویض شرکتی",
    },
    image: "https://images.pexels.com/photos/7587879/pexels-photo-7587879.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    gallery: ["https://images.pexels.com/photos/7587879/pexels-photo-7587879.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"],
    cadAvailable: true,
    isPopular: true,
  },
  {
    id: "fl-turf",
    code: "CK-FL-TRF",
    name: "چمن مصنوعی پرتراکم هلندی مخصوص روف‌گاردن (۳۵ میلی‌متر)",
    category: "flooring",
    categoryName: "کف‌سازی مدولار",
    shortDesc: "چمن مصنوعی ۴ بافت با حس طبیعی چمن بهاره، لایه زهکشی زیرین و مقاوم در برابر لگدمال شدن.",
    fullDesc: "چمن مصنوعی تخصصی چکادبام دارای بکینگ نفوذپذیر آب با سوراخ‌های درین پرتعداد است که حتی در شدیدترین بارش‌ها دچار حوضچه آب نمی‌شود. نخ‌های C شکل پلی‌اتیلن مقاومت بالایی در برابر فشرده شدن دارند.",
    dimensions: { width: 1.0, depth: 1.0, height: 0.035, unitString: "هر مترمربع" },
    weightKg: 3.8,
    deadLoadRating: "light",
    priceEstToman: 1100000,
    materials: {},
    model3D: {
      shapeType: "deck_tile",
      primaryColor: "#15803d",
      secondaryColor: "#166534",
    },
    features: [
      "نرمی فوق‌العاده مناسب برای راه رفتن با پای برهنه و بازی کودکان",
      "ضد پرتوهای فرابنفش و بدون تغییر رنگ طی ۱۰ سال",
      "شستشوی آسان با آب معمولی",
    ],
    specs: {
      "ارتفاع پرز": "۳۵ میلی‌متر",
      "تراکم طولی و عرضی": "۱۸,۹۰۰ گره در مترمربع",
      "گارانتی": "۵ سال ثبات رنگ و دوام الیاف",
    },
    image: "https://images.pexels.com/photos/7722163/pexels-photo-7722163.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    gallery: ["https://images.pexels.com/photos/7722163/pexels-photo-7722163.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200"],
    cadAvailable: true,
  },

  // 7. Outdoor Kitchen & Accessories
  {
    id: "bbq-modular",
    code: "CK-BBQ-MOD",
    name: "کانتر و باربیکیو ماژولار استیل و چوب‌پلاست",
    category: "accessories",
    categoryName: "تجهیزات و اکسسوری",
    shortDesc: "پکیج آشپزی فضای باز با باربیکیو گازی و ذغالی، سینک شستشو و کابینت ضدآب.",
    fullDesc: "لذت دورهمی و باربیکیو روی بام با کانتر مهندسی شده چکادبام. محفظه تعبیه شده برای مخزن گاز، تخته برش چوبی ترموود و درب‌های آرام‌بند ضدآب.",
    dimensions: { width: 1.8, depth: 0.65, height: 0.9, unitString: "۱۸۰ × ۶۵ × ۹۰ سانتی‌متر" },
    weightKg: 95,
    deadLoadRating: "medium",
    priceEstToman: 26500000,
    materials: {
      wpcColors: WPC_COLORS,
      metalColors: METAL_COLORS,
    },
    model3D: {
      shapeType: "bbq",
      primaryColor: "#1e293b",
      secondaryColor: "#cbd5e1",
    },
    features: [
      "شعله‌ورهای استیل نگیر ۳۰۴ ضدزنگ با دریچه‌های تنظیم هوا",
      "سینک و شیر اهرمی تمام استیل مقاوم در برابر یخبندان",
      "صفحه کانتر گرانیت یا چوب‌پلاست ضدحرارت",
    ],
    specs: {
      "تعداد مشعل": "۴ مشعل گازی + ۱ اجاق جانبی سرخ‌کن",
      "کابینت": "اسکلت آلومینیوم با رویه WPC",
      "گارانتی": "۵ سال",
    },
    image: "/images/products/bbq-modular-counter.svg",
    gallery: [
      "/images/products/bbq-modular-counter.svg",
      "https://images.pexels.com/photos/19923727/pexels-photo-19923727.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    cadAvailable: true,
    isPopular: true,
  },
  {
    id: "umb-octa",
    code: "CK-UMB-300",
    name: "چتر سایبان هیدرولیک پایه‌کنار ۳ متری",
    category: "accessories",
    categoryName: "سایبان و پرگولا",
    shortDesc: "سایبان گردان ۳۶۰ درجه با بازشوی جک هیدرولیکی، پایه مخزنی سنگین ضدواژگونی و پارچه آب‌گریز Sunbrella.",
    fullDesc: "سایبان پایه‌کنار هیدرولیک چکادبام با قطر ۳۰۰ سانتی‌متر به شما اجازه می‌دهد بدون مزاحمت ستون در وسط مبلمان یا میز، سایه‌اندازی وسیعی در روف‌گاردن ایجاد کنید. دارای بازوی آفست آلومینیومی سنگین با رنگ کوره‌ای، مفصل چرخش ۳۶۰ درجه با پدال پایی، جک گازی هیدرولیکی برای باز و بسته شدن روان و مخزن وزنی چرخ‌دار ۱۲۰ کیلوگرمی پرتابل.",
    dimensions: { width: 3.0, depth: 3.0, height: 2.65, unitString: "قطر ۳۰۰ × ارتفاع ۲۶۵ سانتی‌متر" },
    weightKg: 85,
    deadLoadRating: "medium",
    priceEstToman: 15400000,
    materials: {
      metalColors: METAL_COLORS,
    },
    model3D: {
      shapeType: "umbrella",
      primaryColor: "#f5f2eb",
      secondaryColor: "#18181b",
    },
    features: [
      "پارچه نانو آکریلیک ضدآب و ضد اشعه UV با ثبات رنگ ۵ ساله",
      "جک هیدرولیکی کمکی جهت باز و بسته شدن بدون نیاز به نیروی زیاد",
      "پایه چرخ‌دار سنگین پرتابل با ترمز قفل‌کننده چرخ",
      "گردش ۳۶۰ درجه زاویه سایه با فشردن پدال پایینی",
      "استراکچر مقاوم در برابر بادهای تا ۶۵ کیلومتر بر ساعت",
    ],
    specs: {
      "قطر چتر": "۳۰۰ سانتی‌متر (۳ متر مفید)",
      "جنس پارچه": "Sunbrella اکریلیک ۳۰۰ گرمی ضدقارچ و آب‌گریز",
      "جنس ستون و بازو": "آلومینیوم اکستروژن آنودایز شده با رنگ الکترواستاتیک مشکی مات",
      "پایه": "مخزن پلی‌اتیلن پر شونده با آب یا بتن (وزن کل با آب: ۱۲۰ کیلوگرم)",
      "گارانتی": "۳ سال گارانتی بدنه و پارچه",
    },
    image: "/images/products/umbrella-cantilever.svg",
    gallery: [
      "/images/products/umbrella-cantilever.svg",
      "https://images.pexels.com/photos/27626177/pexels-photo-27626177.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200",
    ],
    cadAvailable: true,
    isPopular: true,
  },
];

export const CATEGORIES = [
  { id: "all", name: "همه محصولات" },
  { id: "planting", name: "سیستم کاشت مدولار" },
  { id: "furniture", name: "مبلمان فضای باز" },
  { id: "structures", name: "پرگولا و سایبان" },
  { id: "water_fire", name: "آبنما و آتشدان" },
  { id: "lighting", name: "روشنایی و برق" },
  { id: "flooring", name: "کف‌سازی و تایل WPC" },
  { id: "accessories", name: "باربیکیو و اکسسوری" },
];
